version: '3.8'

services:
  libreoffice-dev:
    image: libreoffice-dev:latest
    container_name: libreoffice-dev-gui
    privileged: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./:/source:ro
      - libreoffice-build:/build
      - libreoffice-ccache:/ccache
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - CCACHE_DIR=/ccache
      - DISPLAY=${DISPLAY:-172.28.160.1:0.0}
      - LIBGL_ALWAYS_SOFTWARE=1
      - SAL_USE_VCLPLUGIN=gen
    working_dir: /build
    stdin_open: true
    tty: true
    command: tail -f /dev/null

volumes:
  libreoffice-build:
    external: true
    name: core-master_libreoffice-build
  libreoffice-ccache:
    external: true
    name: core-master_libreoffice-ccache