version: '3.8'

services:
  libreoffice-dev:
    image: ubuntu:24.04
    container_name: libreoffice-dev
    volumes:
      - ./:/source:ro
      - libreoffice-build:/build
      - libreoffice-ccache:/ccache
      # WSLg support
      - /mnt/wslg:/mnt/wslg
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - CCACHE_DIR=/ccache
      - DISPLAY=:0
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
      - PULSE_SERVER=/mnt/wslg/PulseServer
      - DEBIAN_FRONTEND=noninteractive
    working_dir: /build
    command: |
      bash -c "
        echo 'Installing build dependencies...'
        apt-get update && apt-get install -y \
          build-essential \
          git \
          autoconf \
          automake \
          libtool \
          pkg-config \
          python3-dev \
          bison \
          flex \
          libx11-dev \
          libxml2-dev \
          libxslt1-dev \
          libgtk-3-dev \
          libcups2-dev \
          libfontconfig1-dev \
          zip \
          ccache \
        && if [ ! -f /build/.initialized ]; then
          echo 'First time setup - copying source files...'
          cp -r /source/* /build/
          touch /build/.initialized
        fi
        cd /build
        echo 'Running autogen.sh...'
        ./autogen.sh --without-java --without-help --without-myspell-dicts --with-parallelism=4
        echo 'Building LibreOffice...'
        make -j4
        echo 'Build complete!'
        echo 'To run: docker exec libreoffice-dev /build/instdir/program/soffice'
        tail -f /dev/null
      "

volumes:
  libreoffice-build:
  libreoffice-ccache: